### ISSUE TITLE
OOM using RTX 2080

### ISSUE THREAD

**Issue by clw5180** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#1]
I cropped 800x800, overlap=200, and get oom for a few steps(~ 300). I never meet this problem when training on your R2CNN project, even cropped to 1024x1024. Does RetinaNet need more memory?  How to deal with this problem......

**Comment by yangxue0827** [comment]
retinanet的anchor很多，如果你选的是R的anchor形式，又是这么大的图就非常耗显存 @clw5180

**Comment by clw5180** [comment]
> retinanet的anchor很多，如果你选的是R的anchor形式，又是这么大的图就非常耗显存 @clw5180

Thanks a lot, I forget that there are a lot more anchors of RetinaNet. And I try to use a little bit smaller size in cfg.py, it worked.
