### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by CindyHuang23** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#11]
配置文件cfgs.py中 IMG_SHORT_SIDE_LEN ，IMG_MAX_LENGTH 两个参数是什么含义？如果我训练的数据集图片大小为1024*1024的话，这两个参数需要修改马？其他文件需要修改吗？

**Comment by yangxue0827** [comment]
代码已更新 @CindyHuang23 
这两个参数是网络训练实际的大小
