### ISSUE TITLE
训练了550k steps，使用默认配置文件在DOTA v1.0上测试mAP只有0.49

### ISSUE THREAD

**Issue by clw5180** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#12]
很奇怪，我按照作者大佬提供的配置文件没有做修改，直接拿来训练DOTA，但是比正常情况低了10个点，然后我看了每一类的情况，像small-vehicle ，mAP应该能达到**0.66**，但我这里mAP只有**0.18**，之前做R2CNN也是small-vehicle的mAP非常低，然后整体mAP差不多低了10个点。我怀疑是否给的anchor的size太大了，检测不到小物体？另外是否还要手动改下cfg.py的参数才能达到给出的mAP？
我是用的一块RTX2080进行测试，下面是我的预测时保存的几张图片，有些效果很好基本都能检测到，有些就很明显一个small-vehicle都没检测到，想请教下可能是什么原因造成的？
（前两张图效果还行，后面两张图，所有small-vehicle都没检测到）
![](https://github.com/clw5180/TensorFlow_Practice_resource/blob/master/RetinaNet_Tensorflow_Rotation/P0199_1.png)

![](https://github.com/clw5180/TensorFlow_Practice_resource/blob/master/RetinaNet_Tensorflow_Rotation/P0454_1.png)

![](https://github.com/clw5180/TensorFlow_Practice_resource/blob/master/RetinaNet_Tensorflow_Rotation/P0257_1.png)

![](https://github.com/clw5180/TensorFlow_Practice_resource/blob/master/RetinaNet_Tensorflow_Rotation/P0261_1.png)

**Comment by yangxue0827** [comment]
如果两个代码车都低应该是有问题了，我试验的时候没有遇到这个问题，这个代码在SV LV SH三类都会挺高的 @clw5180   另外我更新的代码

**Comment by clw5180** [comment]
> 如果两个代码车都低应该是有问题了，我试验的时候没有遇到这个问题，这个代码在SV LV SH三类都会挺高的 @clw5180 另外我更新的代码

非常感谢，想再请教一下：
1. resnet50_v1d是怎么来的，和官方的resnet50_v1相比是参数更多了么？我之前用的是resnet50_v1
2. readme提到配置是600 -> 800，我给改成600 -> 600 了，这个有什么影响呢，会不会对小目标不好？既然测试阶段也是用的600为什么训练时候要放大到800？
3. 如果显存够用的情况下，要想在DOTA数据集提升精度可以尝试修改哪些参数？之前cfg.py中， ANCHOR_RATIOS配置了从1~7，另外ANCHOR_SCALES现在只有[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]，是否可以考虑多配置几个小一点的值，比如0.1 0.5之类的，对小目标能否有提升？我还会再多做几次实验

**Comment by yangxue0827** [comment]
1、resnet50_v1d是从gluoncv那转换过来的，代码两个都支持使用
2、600->800是基于小目标的考虑，毕竟RetinaNet不是用P2
3、想要小目标训练好，采样是否充足是很关键的，我给的参数是RetinaNet默认的参数，你当然可以调整。我这个代码只是当一个baseline，并不一定是最优的。 @clw5180

**Comment by clw5180** [comment]
> 1、resnet50_v1d是从gluoncv那转换过来的，代码两个都支持使用
> 2、600->800是基于小目标的考虑，毕竟RetinaNet不是用P2
> 3、想要小目标训练好，采样是否充足是很关键的，我给的参数是RetinaNet默认的参数，你当然可以调整。我这个代码只是当一个baseline，并不一定是最优的。 @clw5180

再次感谢！我发现更新后 cfg.py 中 NMS_IOU_THRESHOLD = 0.1，是不是太小了，这个值一般不都是取0.5或者以上么  @yangxue0827

**Comment by yangxue0827** [comment]
测试脚本里这个阈值不同类单独设置了，这里这个只是用在tensorboard的可视化。 @clw5180

**Comment by clw5180** [comment]
> 测试脚本里这个阈值不同类单独设置了，这里这个只是用在tensorboard的可视化。 @clw5180

我看了一下代码，感觉 tensorboard可视化应该是在 VIS_SCORE = 0.4配置 ？ NMS_IOU_THRESHOLD 应该判断RPN的anchor是否与GT关联的吧
```
## proposal_opr.py
def filter_detections(boxes, scores, is_training):
    """
    :param boxes: [-1, 4]
    :param scores: [-1, ]
    :param labels: [-1, ]
    :return:
    """
    if is_training:
        indices = tf.reshape(tf.where(tf.greater(scores, cfgs.VIS_SCORE)), [-1, ])
    else:
        indices = tf.reshape(tf.where(tf.greater(scores, cfgs.FILTERED_SCORE)), [-1, ])

    if cfgs.NMS:
        filtered_boxes = tf.gather(boxes, indices)
        filtered_scores = tf.gather(scores, indices)

        # perform NMS

        nms_indices = nms_rotate.nms_rotate(decode_boxes=filtered_boxes,
                                            scores=filtered_scores,
                                            iou_threshold=cfgs.NMS_IOU_THRESHOLD,
                                            max_output_size=100,
                                            use_angle_condition=False,
                                            angle_threshold=15,
                                            use_gpu=False)

        # filter indices based on NMS
        indices = tf.gather(indices, nms_indices)

    # add indices to list of all indices
    return indices
```

**Comment by 864546664** [comment]
请问在哪个个文件上测的map，是作者提供的还是你自己写的呢
