### ISSUE TITLE
Please do not use baidu netdisk to store models

### ISSUE THREAD

**Issue by WangXiaoLongNWPU** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#13]
Your work is very helpful. Well done! But it is frustrating to wait for an hour to download a 100MB file. It makes me feel that I'm living in twenty years ago.

**Comment by yangxue0827** [comment]
抱歉，我没有其他地方可以传，如果你下载缓慢，我readme里已经提供了两种方式
1.使用之前老版本的权重，在tf的github上，我提供了链接，下载比较快
2.如果想使用新的权重你也可以自己转换，转换的代码链接都给了。

**Comment by bigKoki** [comment]
网上有破解限速的方法，而且大家都是中国人，说中文就行了，hahaha

**Comment by WangXiaoLongNWPU** [comment]
Thank you.
