### ISSUE TITLE
About train batchsize > 1 in one GPU?

### ISSUE THREAD

**Issue by ztyxd** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#15]
Does this code support train in one GPU with 2 batchsize?

I find that in multi-gpu-read-tfrecord.py it does not limit the batchsize, while in the read-tf-record.py, it limits that batchsize must be 1.

So, can I train with 2 batchsize in one GPU?

**Comment by yangxue0827** [comment]
Batch size>1 is not supported at this time. I wrote the code for batchsize>1, but the training was slower, so I didn't upload it. @ztyxd

**Comment by ztyxd** [comment]
@yangxue0827  Thank you very much!!!
