### ISSUE TITLE
Missing trained weights ?

### ISSUE THREAD

**Issue by Kemonius** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#18]
Hi,

Many thanks for the great repo. However I have noticed that the link in the trained_weigths README.md ( https://github.com/DetectionTeamUCAS/Models/RetinaNet_Tensorflow ) seems to be a 404. Do you plan to publish the weights for your detector, now or in the future ?

Thanks again for the code :)

**Comment by yangxue0827** [comment]
For some reasons, the trained weights of this repo are not available for the time being.

**Comment by Kemonius** [comment]
Alright thanks !
