### ISSUE TITLE
Import rbbx_overlaps fails

### ISSUE THREAD

**Issue by WangXiaoLongNWPU** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#19]
When I ran "python multi_gpu_train.py", I got an error importing rbbx_overlaps as follows

Traceback (most recent call last):
  File "hello_world.py", line 17, in <module>
    from libs.networks import build_whole_network
  File "../libs/networks/build_whole_network.py", line 13, in <module>
    from libs.losses import losses
  File "../libs/losses/losses.py", line 9, in <module>
    from libs.box_utils.iou_rotate import iou_rotate_calculate2
  File "../libs/box_utils/iou_rotate.py", line 10, in <module>
    from libs.box_utils.rbbox_overlaps import rbbx_overlaps
ImportError: ../libs/box_utils/rbbox_overlaps.cpython-35m-x86_64-linux-gnu.so: failed to map segment from shared object

All my packages have the correct versions. I have run the "python setup.py build_ext --inplace" commands to generate those .so files. Any suggestions?

By the way, I use English since my laptop has no Pinyin input. Please feel free to reply in Chinese. Thank you.

**Comment by yangxue0827** [comment]
你先删掉所有.so和.cpp文件再重新编译一次试试 @WangXiaoLongNWPU

**Comment by WangXiaoLongNWPU** [comment]
I already done it several times. It didn't work.

**Comment by WangXiaoLongNWPU** [comment]
Can you share the weights after training on DOTA dataset? Then I can test without training. Also can you show me the link of the original author of the files in libs/box_utils/ so that I can try their code to track the problem.

**Comment by yangxue0827** [comment]
你搜rrpn原作者的repo就可以找到 @WangXiaoLongNWPU

**Comment by WangXiaoLongNWPU** [comment]
I have solved the problem by moving the code from the disk in /mnt/... to ~/Desktop. I don't know why but it works then. Thank you for the help!
