### ISSUE TITLE
could you please tell me how to deal with the import problem？

### ISSUE THREAD

**Issue by bigKoki** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#2]
ModuleNotFoundError: No module named 'libs.box_utils.rbbox_overlaps'

i see the relevant set in setup.py,but i cannot import the .cpp file，could you please tell me that what makes this problem?

**Comment by yangxue0827** [comment]
cd $PATH_ROOT/libs/box_utils/cython_utils
python setup.py build_ext --inplace (or make)

cd $PATH_ROOT/libs/box_utils/
python setup.py build_ext --inplace

@864546664

**Comment by bigKoki** [comment]
> cd $PATH_ROOT/libs/box_utils/cython_utils
> python setup.py build_ext --inplace (or make)
> 
> cd $PATH_ROOT/libs/box_utils/
> python setup.py build_ext --inplace
> 
> @864546664

多谢，之前没看到要在linux下运行，是我大意了
