### ISSUE TITLE
Error of loading checkpoint when training finished

### ISSUE THREAD

**Issue by WangXiaoLongNWPU** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#20]
Here is the lines I changed in my cfgs.py

VERSION = 'resnet_v1_50_20190729' # a new name
NET_NAME = 'resnet50_v1d'  # 'MobilenetV2'

Then I started to train and had a series of files in ./output/trained_weights/resnet_v1_50_20190729, including:
checkpoints
DOTA_1000model.ckpt.meta
DOTA_1000model.ckpt.index
DOTA_1000model.ckpt.data-00000-of-00001
etc.

Then I tested and got following errors:
2019-07-29 21:13:08.984880: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key resnet50_v1d/C1/conv0/BatchNorm/beta not found in checkpoint
...
tensorflow.python.framework.errors_impl.NotFoundError: Key resnet50_v1d/C1/conv0/BatchNorm/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]
...
tensorflow.python.framework.errors_impl.NotFoundError: Key resnet50_v1d/C1/conv0/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at ../libs/networks/build_whole_network.py:286) ]]
...
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint
...

This error is similar to [#14](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/issues/14). I put those DOTA_1000model.ckpt files into ./data/pretrained_weights and it didn't help. Any suggestions?

**Comment by xliu79** [comment]
I also met the same problem. Did you find the solution about this problem?????

**Comment by yangxue0827** [comment]
folder /data/pretrained_weights is for pretrained_weights rather than trained_weight!!! @ @WangXiaoLongNWPU @xliu79

**Comment by WangXiaoLongNWPU** [comment]
Hi @xliu79 ,
This is a path setting problem. The instruction was vague and I didn't figure it out. So I gave up. 
You can try the author's another work named R2CNN-Plus-Plus_Tensorflow. I tried it instead and it worked fine. After training, the newly generated weights could be loaded successful. This is all I know.

**Comment by xliu79** [comment]
> Hi @xliu79 ,
> This is a path setting problem. The instruction was vague and I didn't figure it out. So I gave up.
> You can try the author's another work named R2CNN-Plus-Plus_Tensorflow. I tried it instead and it worked fine. After training, the newly generated weights could be loaded successful. This is all I know.

Thanks

**Comment by xliu79** [comment]
> folder /data/pretrained_weights is for pretrained_weights rather than trained_weight!!! @ @WangXiaoLongNWPU @xliu79

作者您好，我是一开始就遇到的这个问题，加载的时候就出现的，已经按照文档把.ckpt文件放到pretrained_weights里面了

**Comment by xliu79** [comment]
解决了 需要把代码中网络名称改为和下载下来的模型文件一样的名称，而不是把模型文件重命名。我之前是把模型文件重命名的..
