### ISSUE TITLE
采用更新后的代码进行训练 检测结果图片上没有画框结果

### ISSUE THREAD

**Issue by qzq-hit** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#21]
1.我采用的是更新后的代码进行训练，先将训练集图片进行裁剪 裁剪后有两万多张 由于我的gpu很差速度很慢目前只训练了5k步 但我用训练结果进行测试 图片上完全没有结果 是哪里有问题吗（虽然没到一个epoch 但一个结果都没有总感觉有些奇怪）
2.我用tensorboard查看训练结果 totalloss降到了0.9左右 gtboxes_h和gtbox_r都有框 但是final_detection完全没有框 这种结果是正常的吗？

**Comment by yangxue0827** [comment]
retinanet前几个epoch不出框比较正常，而且我还加了warmup，一般要训练两三个epoch @qzq-hit

**Comment by qzq-hit** [comment]
感谢您的回复 那我接着训练几个epoch 再给您反馈 非常感谢

**Comment by yangxue0827** [comment]
嗯，应该没啥大的问题，我看有人已经出效果了，结果还挺正常的 @qzq-hit

**Comment by yangxue0827** [comment]
请问有效果了吗 @qzq-hit

**Comment by ouy1989** [comment]
@yangxue0827 大佬您好，我用了你的代码，测试时，为什么dota_res中各个类别.txt有坐标，而dota_img_vis图片中只有一张图中plane有画框，我是不是哪里操作错了？谢谢

**Comment by yangxue0827** [comment]
画图有卡分数的阈值 @ouy1989

**Comment by ouy1989** [comment]
@yangxue0827 谢谢大佬，看到了，我训练了13万step，报错MemoryError，可能训练不够，导致置信度低，从而没有画框在图上，请问怎么可避免MemoryError？

**Comment by yangxue0827** [comment]
减少anchor，或者用较小的backbone，置信度一般在第一次降学习率之后会变高。 @ouy1989

**Comment by ouy1989** [comment]
@yangxue0827 好的，谢谢，我试试哈。

**Comment by qzq-hit** [comment]
> 请问有效果了吗 @qzq-hit

1.我训练了5个epoch之后通过tensorboard察看发现final_detection是有结果的 而且结果还可以 但是我test的时候无论是输出图像还是txt都是没有结果 不太清楚问题出在哪里
2.请问cfg中的vis_score是画图的阈值吗 我更改为0.001后依旧没有结果
如果您能给出改正建议的话将万分感激

**Comment by ouy1989** [comment]
@yangxue0827 大佬，我今天训练了540K，去测试的时候，会生成dota_img_vis文件，图片上效果还可以，但是不知道为什么没有生成dota_res文件？上次训练测试，两个文件夹都会生成，这次不知道为什么少了dota_res文件。谢谢！

**Comment by ouy1989** [comment]
@yangxue0827 大佬，麻烦问一下，测试的dota_res中.txt文件中，为什么有的坐标是负值？谢谢

**Comment by yangxue0827** [comment]
有些目标在边界处就出现负数了 @ouy1989

**Comment by yangxue0827** [comment]
1、确认测试的时候加载的是训练好的权重吗
2、多训练一会
@qzq-hit
