### ISSUE TITLE
关于 batch_size和epoch

### ISSUE THREAD

**Issue by choimroc** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#24]
您好！打扰了！我想请教一下两个问题问题。
在这份代码中：
一次 epoch 是否是遍历完一次 所有sample？
如果是这样的话，遍历完一次所需要的 step 是否是等于 sample/batch_size？

因为我相修改batch_size～～
感谢！

**Comment by yangxue0827** [comment]
还要除以gpu数量 @choimroc
