### ISSUE TITLE
输入图片尺寸，学习率设置相关问题

### ISSUE THREAD

**Issue by 18804601171** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#25]
作者你好，输入图片尺寸必须是600或者800吗，另外学习率在设置的时候与gpu的数量及batch_size有什么关系

**Comment by yangxue0827** [comment]
1、图片大小没有限制，你可以根据你显卡显存来调整。
2、一般lr=base lr * batch size * num gpu。但是这个repo通过这样方式训练经常出现nan，因此我没有采用。 @18804601171

**Comment by 18804601171** [comment]
我用的默认配置，数据集是DOTA，训练的时候loss还是有nan或者reg loss 出现0.000

**Comment by yangxue0827** [comment]
你用的是最新更新后的代码吗？ @18804601171

**Comment by 18804601171** [comment]
是的

**Comment by yangxue0827** [comment]
最好严格按照我的步骤来，代码很多人已经跑成功了，而且点能对上 @18804601171

**Comment by zhouzhubin** [comment]
@18804601171 你好，请问你现在解决了吗？我输入尺寸为400，就会出现nan，我后面又训练了600,800这两个都可以，没有出现loss为nan 的情况
