### ISSUE TITLE
训练自己数据出现了out of memory 

### ISSUE THREAD

**Issue by 18804601171** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#27]
我已经在DOTA数据集下跑通了默认配置，但是换了自己的数据，和DOTA数据差不多，也是遥感的，就会出现
out of memory
invalid argument
an illegal memory access was encountered
an illegal memory access was encountered

**Comment by bezero** [comment]
I had similar problem when training with `METHOD = 'R'`. Changing back to `METHOD = 'H'` solved the issue. However, I want to train using `R` method. Is there any idea how to solve this problem?

**Comment by yangxue0827** [comment]
减小图片大小或者减少anchor数量，当然最好是用大显存卡跑 @18804601171
