### ISSUE TITLE
cfgs file for ResNet152_v1 ... 

### ISSUE THREAD

**Issue by dexception** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#31]
Hi,

Can you share the cfgs file for ResNet152_v1  the most accurate model ?
I would like to try this on my dataset.

**Comment by yangxue0827** [comment]
https://github.com/tensorflow/models/blob/master/research/slim/README.md

**Comment by dexception** [comment]
@yangxue0827 
My bad. You haven't released R3DET as of yet ? have you ? 
I am looking for the DOTA cfgs for ResNet152_v1 model.

**Comment by yangxue0827** [comment]
R3Det will be open source after the paper is accepted and will be placed under this organization: https://github.com/orgs/Thinklab-SJTU  @dexception

**Comment by dexception** [comment]
Thanks for the update !

**Comment by SumanthReddyKaliki** [comment]
Hi, any updates on releasing R3Det?
