### ISSUE TITLE
About implementation of Feature refinement Module

### ISSUE THREAD

**Issue by smingscript** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#35]
Hello, thank you for your wonderful works!
I have an question about where can i find the implementation code of FRM, which can found in your paper, from your source! 
thank you! :)

**Comment by yangxue0827** [comment]
paper：https://arxiv.org/abs/1908.05612
code： https://github.com/SJTU-Det/R3Det_Tensorflow （not available now）
@smingscript

**Comment by smingscript** [comment]
ok i got it! i'm looking forward your implementation :) thank you!
