### ISSUE TITLE
预训练模型文件

### ISSUE THREAD

**Issue by hlf1996** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#36]
请问resnet101_v1d.ckpt和resnet50_v1d.ckpt这两个文件应该在哪下载，里面提供的链接下载不了了

**Comment by yangxue0827** [comment]
[google drive](https://drive.google.com/drive/folders/1BM8ffn1WnsRRb5RcuAcyJAHX8NS2M1Gz)
@hlf1996
