### ISSUE TITLE
数据类型的问题

### ISSUE THREAD

**Issue by hlf1996** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#37]
在更换数据集时总是出现
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 8, current size 0) 错误，请问应该如何解决这个问题。

**Comment by yangxue0827** [comment]
你生成的tfrecord应该有问题，一种是找不到路径，一种是你数据有问题需要检查一下。
