### ISSUE TITLE
回归loss nan

### ISSUE THREAD

**Issue by Vickeyhw** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#38]
你好，请问训练retinanet回归旋转框时，loss下降的很稳定，然后突然回归部分的loss变成nan或者inf,debug发现从backbone出来的特征图已经nan了，可能是什么原因呢？调低学习率也没有解决

**Comment by yangxue0827** [comment]
自己的数据集还是DOTA？ @Vickeyhw

**Comment by Vickeyhw** [comment]
@yangxue0827 DOTA

**Comment by yangxue0827** [comment]
是用我提供的配置文件参数还是你自己修改后的？ @Vickeyhw

**Comment by Vickeyhw** [comment]
@yangxue0827 用maskrcnn-benchmark改的，用你的配置文件参数

**Comment by yangxue0827** [comment]
那我也不清楚为什么了，应该是哪里复现的问题吧。 @Vickeyhw
