### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Vickeyhw** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#39]
error information:

python setup.py build_ext --inplace
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
skipping 'nms.c' Cython extension (up-to-date)
building 'cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.7
{'gcc': ['-Wno-cpp', '-Wno-unused-function']}
gcc -pthread -B /home/huangwei/anaconda3/envs/tensorflow-R3det/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/huangwei/anaconda3/envs/tensorflow-R3det/lib/python3.7/site-packages/numpy/core/include -I/home/huangwei/anaconda3/envs/tensorflow-R3det/include/python3.7m -c bbox.c -o build/temp.linux-x86_64-3.7/bbox.o -Wno-cpp -Wno-unused-function
bbox.c: In function ‘__Pyx__ExceptionSave’:
bbox.c:9439:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     *type = tstate->exc_type;
                   ^
bbox.c:9440:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     *value = tstate->exc_value;
                    ^
bbox.c:9441:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     *tb = tstate->exc_traceback;
                 ^
bbox.c: In function ‘__Pyx__ExceptionReset’:

**Comment by yangxue0827** [comment]
Your Development Environment?
@Vickeyhw
