### ISSUE TITLE
about creating tfrecord from own dataset

### ISSUE THREAD

**Issue by smingscript** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#40]
hello! I have issue on using my own dataset.
> tested the code on tensorflow 1.15.0 version.
> cuda 10.1

I met 

>Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)

error with own dataset tfrecord file.
I used your convert_data_to_tfrecord.py file but I didn't do the data crop before that.
Is this error comes from not cropping my data to 600x600?
and yes my datasets are all have different size...

it would be very thankful to give me some help!

**Comment by yangxue0827** [comment]
Something wrong with your tfrecord. Image cropping is unnecessary, but your annotation format should be the same as mine (xml format). @smingscript

**Comment by smingscript** [comment]
yes you are right! my xml file had wrong information on image size!
I fixed it and it works! thank you!
