### ISSUE TITLE
Simple question about training

### ISSUE THREAD

**Issue by HMCBSJ** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#41]
I am successfully training with a minor issue under cuda 10 and TensorFlow 1.14. environment.
I want to ask two things

1. Does this code have Total epochs to automatically end the training or keep going unless I stop by myself?
but I can see It does save the weight in the middle of training and how many iterations are for one epoch.
------------------------------------------ Train config
RESTORE_FROM_RPN = False
FIXED_BLOCKS = 1  # allow 0~3
FREEZE_BLOCKS = [True, False, False, False, False]  # for gluoncv backbone
USE_07_METRIC = True

MUTILPY_BIAS_GRADIENT = 2.0  # if None, will not multipy
GRADIENT_CLIPPING_BY_NORM = 10.0  # if None, will not clip

CLS_WEIGHT = 1.0
REG_WEIGHT = 1.0
USE_IOU_FACTOR = False

BATCH_SIZE = 1
EPSILON = 1e-5
MOMENTUM = 0.9
LR = 5e-4
DECAY_STEP = [SAVE_WEIGHTS_INTE*12, SAVE_WEIGHTS_INTE*16, SAVE_WEIGHTS_INTE*20]
**MAX_ITERATION = SAVE_WEIGHTS_INTE*20**
WARM_SETP = int(1.0 / 4.0 * SAVE_WEIGHTS_INTE)

2. Another question is about a warning issue, Do you have any idea if it is bad enough to influence the result or not? Thanks in advance!

**Issue is below**
WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fb846a0c550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, setthe verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound methodConv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fb846a0c550>>: AssertionError: Bad argument numberfor Name: 3, expecting 4

**Comment by yangxue0827** [comment]
1. iterations per epoch (we save weight per epoch): [SAVE_WEIGHTS_INTE](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/libs/configs/cfgs.py#L53)
2.  total epochs: [MAX_ITERATION](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/libs/configs/cfgs.py#L87)
3. I don't pay attention to this warning, so I don't know. My development environment is cuda10+tf1.13

@HMCBSJ
