### ISSUE TITLE
关于IOU问题计算问题

### ISSUE THREAD

**Issue by weihancug** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#44]
你好，我在[iou_rotate.py](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/libs/box_utils/iou_rotate.py)中看到，这里计算使用的是opencv来计算overlap，为什么没用gpu呢， 这两个计算方式有什么差别吗

**Comment by yangxue0827** [comment]
里面有gpu的[代码](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/libs/box_utils/iou_rotate.py#L26) @weihancug

**Comment by weihancug** [comment]
@yangxue0827   两种计算有什么区别吗 因为本项目里面看到默认调用的OpenCV的，opencv有一个bug: -215：Assertion failed intersection.size ()<= 8 in function 'rotatedrectangleintersection

**Comment by yangxue0827** [comment]
opencv无法处理完全重合的两个框的面积计算，项目里这个报错是我抛出来的，我已经做了处理，不影响结果。 @weihancug

**Comment by weihancug** [comment]
方便指出来改在哪里了吗，因为目前 报了这个错 无法运行 ， 或者直接改成运行gpu版本的是不是就可以了 ？

**Comment by yangxue0827** [comment]
捕获这种情况，直接赋值1。你都可以用。 @weihancug

**Comment by weihancug** [comment]
gpu和opencv 代码都可以用吗 ，两者是不是没啥区别。。 然后这个异常在哪里捕获- -，代码加在哪里，，，，（可不可以看清楚问题在回答我）。。。。。

**Comment by yangxue0827** [comment]
[这里是cpu版异常情况处理](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/libs/box_utils/nms_rotate.py#L84) 
以及
[这里是GPU版输入的抖动，消除完全重合的情况](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/test_dota.py#L154)

PS：不是时刻在电脑旁边的，一般都是通过邮件回复，无法及时给出具体代码的地方，所以建议你自己先认真阅读代码。
@weihancug

**Comment by yangxue0827** [comment]
两个区别不大，在大量运算的时候，建议用gpu比较快，量少的话都可以的 @weihancug

**Comment by weihancug** [comment]
明白了，感谢答疑，感谢！！！
