### ISSUE TITLE
What is the difference between anchor_utils.make_anchors and generate_anchors.generate_anchors_pre?

### ISSUE THREAD

**Issue by zhangjinsong3** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#45]
I am freezing the trained weights to pb for C++ use, but the py_function 'generate_anchors_pre' can not be frozen.So i need to use a tf function of 'make_anchors'. 
I found that in anchor_utils, there already has one, but you did not use it. So if there is any problem in the function 'anchor_utils.make_anchors' ?

**Comment by yangxue0827** [comment]
It should be fine, you can try it, @zhangjinsong3
