### ISSUE TITLE
from libs.box_utils.cython_utils.cython_bbox import bbox_overlaps报错

### ISSUE THREAD

**Issue by lilycy0580** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#48]
作者你好，这里代码报错是怎么回事
![image](https://user-images.githubusercontent.com/58139224/70774230-90454900-1db4-11ea-8d3a-755156480822.png)

**Comment by yangxue0827** [comment]
没事的，就是这样，正常用。

**Comment by ZOUYIyi** [comment]
> 没事的，就是这样，正常用。

大神你好，这个代码可以用您训练好的weight去预测一张图吗？

**Comment by yangxue0827** [comment]
当然是可以的，但是我只提供的是训练DOTA的权重。

**Comment by ZOUYIyi** [comment]
> 当然是可以的，但是我只提供的是训练DOTA的权重。

我明白，就是我先只需要在dota数据集里面的图上看一看预测效果，然后再看怎么训练自己的数据。不过加载dota的权重来预测一张dota的图这一目的，是通过inference.py做到的是吗，但是看readme好像是用的eval_dota.py,但是代码里面evaldota加载的又是在ImageNet上的预训练权重，就有点不明白了。
望告知如何用dota的权重测dota的图

**Comment by ZOUYIyi** [comment]
> 当然是可以的，但是我只提供的是训练DOTA的权重。

大神能不能提供在windows下cython的setup文件。。。。docker里面太难受了。

**Comment by yangxue0827** [comment]
使用test_dota.py，我不知道在windows下怎么弄。

**Comment by lilycy0580** [comment]
> 没事的，就是这样，正常用。

好的谢谢

**Comment by 10207011** [comment]
請問訓練時怎解決這报错?

> 作者你好，这里代码报错是怎么回事
> ![image](https://user-images.githubusercontent.com/58139224/70774230-90454900-1db4-11ea-8d3a-755156480822.png)
