### ISSUE TITLE
训练程序卡在_, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])不动了

### ISSUE THREAD

**Issue by lilycy0580** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#49]
作者你好，我运行训练程序时，程序会卡在下面这句，为什么啊
![image](https://user-images.githubusercontent.com/58139224/70901634-20de8c00-2036-11ea-83a2-f303f231b6e2.png)

**Comment by yangxue0827** [comment]
是不是你tfrecord里没有数据
@lilycy0580

**Comment by lilycy0580** [comment]
> tfrecord里没有数据

按照convert_data_to_tfrecord.py运行生成DOTA_train.tfrecord的，为何会没有数据呢

**Comment by yangxue0827** [comment]
你看一下tfrecord文件的大小 @lilycy0580

**Comment by caoyuanbao** [comment]
> 你看一下tfrecord文件的大小 @lilycy0580

nb

**Comment by yangxue0827** [comment]
一般来说你的数据路径错了，导致我在这个路径没有读到数据，然后生成了一个空的tfrecord。建议单步调试一下。
