### ISSUE TITLE
Sigmoid question

### ISSUE THREAD

**Issue by DMIRICA** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#5]
Little question: Why did you use sigmoid instead of softmax there?
https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/b03a7eafba21bfbb78dbffe1be53ab914080201e/libs/networks/build_whole_network.py#L75

**Comment by yangxue0827** [comment]
You should read RetinaNet first. @DMIRICA
