### ISSUE TITLE
out of memory occurs in 'R' method. An illegal memory access was encountered.

### ISSUE THREAD

**Issue by caoyuanbao** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#52]
作者你好，cfgs_res152_dota_v12.py的Anchor config的METHOD = 'H'，而别的配置文件有写'R'的。我想问一下这个R  H是怎么考虑的，他们想达到的目的效果是什么啊

**Comment by yangxue0827** [comment]
H是水平anchor，R是旋转anchor，具体区别可以看R3Det这篇文章。

**Comment by caoyuanbao** [comment]
> H是水平anchor，R是旋转anchor，具体区别可以看R3Det这篇文章。

我把cfgs里的METHOD改成R之后训练。它总是报错，我用了3张显卡：
![image](https://user-images.githubusercontent.com/18445923/71146144-06d3c200-225f-11ea-8311-127bf51d677c.png)

**Comment by yangxue0827** [comment]
和gpu版本的iou计算函数有关，因为这个函数也会额外使用一些gpu显存，所以可能原因是你先存不够用了。我用R模式也是时跑通时跑不通的，原因还没搞明白，你显存多大？

**Comment by caoyuanbao** [comment]
> 和gpu版本的iou计算函数有关，因为这个函数也会额外使用一些gpu显存，所以可能原因是你先存不够用了。我用R模式也是时跑通时跑不通的，原因还没搞明白，你显存多大？

我用远程服务器跑的，本地电脑没现存。。。。

**Comment by yangxue0827** [comment]
跑代码的时候会显示吧，什么卡都不知道吗？

**Comment by caoyuanbao** [comment]
> 跑代码的时候会显示吧，什么卡都不知道吗？

![image](https://user-images.githubusercontent.com/18445923/71147925-35ed3200-2265-11ea-95a7-10bea6bdbd42.png)
一开始用了3个不行，，全用上居然也不行，，，你这程序到底要多高配置TT...

**Comment by yangxue0827** [comment]
多gpu跑又不是所有显存跑一个程序，是每个gpu跑一个，最后梯度合并同时更新网络。你用的那个cfgs？你要不试试吧cfgs_res50_dota_v4.py的内容然后把他改成R试试，先用一张卡。

**Comment by caoyuanbao** [comment]
> 多gpu跑又不是所有显存跑一个程序，是每个gpu跑一个，最后梯度合并同时更新网络。你用的那个cfgs？你要不试试吧cfgs_res50_dota_v4.py的内容然后把他改成R试试，先用一张卡。

我那个'H'的已经跑通了，也得到模型训练结果了，，就是改成'R'还不行，我试试一个gpu去

**Comment by yangxue0827** [comment]
你加我微信yangxue-0826

**Comment by caoyuanbao** [comment]
> 多gpu跑又不是所有显存跑一个程序，是每个gpu跑一个，最后梯度合并同时更新网络。你用的那个cfgs？你要不试试吧cfgs_res50_dota_v4.py的内容然后把他改成R试试，先用一张卡。

1张 3张 6张都试了，都没开始训练，而且我输出step，程序在哪结束很随机
![image](https://user-images.githubusercontent.com/18445923/71148769-7fd71780-2267-11ea-89f4-f415189e003c.png)

![image](https://user-images.githubusercontent.com/18445923/71148710-54542d00-2267-11ea-92d5-796ec9c9e890.png)

**Comment by yangxue0827** [comment]
The reason was that she used resnet152 and had insufficient memory.
