### ISSUE TITLE
why is the inference time so undulation?

### ISSUE THREAD

**Issue by ZOUYIyi** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#53]
我用inference.py 预测某个文件夹下的几张图片，希望看到预测结果和预测时间，结果作为图片存在另一个目录，预测时间在打印出来，但是同时发现两个问题：
1、检测结果不理想，是否是因为不应该用infenrence.py？
2、检测时间的波动非常大从3s到0.3s，可以优化吗？还是算法本身即是如此？

**Comment by yangxue0827** [comment]
你的图片多大？前几章图片测试时间会不准，因为会算上加载模型等时间，需要图片多一点才行。另外存图会比较占时间。

**Comment by ZOUYIyi** [comment]
@yangxue0827 我利用9张图片测试，其中6张是从3张复制的，同时，在代码里的计算时间只有sess.run()函数的执行过程。
不考虑第一次预测时间。
我发现，时间较多的都是同一张图片，而这张图片的识别效果也是最差的，推测可能是因为识别出了很多框，因此做nms的时候花太长时间。我的图片大小是800*800。要得到最好的效果，我的图片是否需要做预处理？

**Comment by yangxue0827** [comment]
预处理代码做了的。
