### ISSUE TITLE
单张图片的训练问题

### ISSUE THREAD

**Issue by ZOUYIyi** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#58]
我修改了读取训练数据的部分，然后用单张图片进行训练，想看是否能过拟合出这一张图片的目标。

一共有8类，但是这张图片上只出现了5类，7个物体。

发现无论怎么训练，总是有一个物体无法识别到。而我换了另外一张图训练到过拟合就可以全部识别。请问这个可能和什么因素有关呢？

**Comment by yangxue0827** [comment]
我不明白你这样做有什么意义，所以无法给出什么意见，抱歉！ @ZOUYIyi

**Comment by ZOUYIyi** [comment]
> 我不明白你这样做有什么意义，所以无法给出什么意见，抱歉！ @ZOUYIyi

训练单张图片来过拟合网络以验证网络的正确性，我是用来测试我修改的读取数据部分是否正常，谢谢回复。

**Comment by yangxue0827** [comment]
用于debug是可以的，但是用这种方式来判断模型的性能不太可取，还是建议你训练完整的数据集 @ZOUYIyi
