### ISSUE TITLE
感谢你的工作！请问如何使用更强大的backbone，我遇到了问题！

### ISSUE THREAD

**Issue by liugaolian** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#6]

**Comment by liugaolian** [comment]
我想要使用更强大的backbone，从你提供的网盘链接下载了resnet101_v1d相关文件3个，外加1个checkpoint，总共4个文件，放置在ROOT_PATH/output/trained_weights/xxxxx路径下（其中xxxxx是我在cfgs.py中的VERSION），开始训练时提示无法加载模型，不知道怎么回事。谢谢你，期待你的回复。

**Comment by DMIRICA** [comment]
You have to place the resnet ckpt in data/pretrained_weights. The output/trained_weights/xxx is the path where the net will save future checkpoints.

**Comment by liugaolian** [comment]
> You have to place the resnet ckpt in data/pretrained_weights. The output/trained_weights/xxx is the path where the net will save future checkpoints.

**Comment by liugaolian** [comment]
> You have to place the resnet ckpt in data/pretrained_weights. The output/trained_weights/xxx is the path where the net will save future checkpoints.

谢谢，你的意思是说，把网盘链接下载得到的resnet101_v1d.ckpt.index、resnet101_v1d.ckpt.data-00000-of-00001、resnet101_v1d.ckpt.meta和checkpoint这4个文件，放置在data/pretrained_weights/xxxxx路径下吗？（其中xxxxx是我在cfgs.py中的VERSION）

**Comment by yangxue0827** [comment]
xxxx不需要，放在data/pretrained_weights/ @liugaolian

**Comment by liugaolian** [comment]
> xxxx不需要，放在data/pretrained_weights/ @liugaolian 
Thanks very much, it is work!!!
