### ISSUE TITLE
tfrecord里img的格式问题

### ISSUE THREAD

**Issue by zhouzhubin** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#60]
@yangxue0827 大佬你好，在r2cnn++工程里tfrecord中img格式BGR的，但为什么在这个工程却是RGB的，我用r2cnn++中tfrecord训练是可以的，但是模型输入400就会出现nan，而且当旋转nms使用GPU时，某些图片会出现以下错误：
File "rotate_polygon_nms.pyx", line 22, in rotate_polygon_nms.rotate_gpu_nms

IndexError: Out of bounds on buffer access (axis 0)

**Comment by yangxue0827** [comment]
你只要保证训练和测试的图片通道顺序保持一致就行。nan的话可能是你数据有问题，或者是需要调参比如调低学习率。 @zhouzhubin
