### ISSUE TITLE
Reg loss nan

### ISSUE THREAD

**Issue by PURE-melo** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#62]
Thanks for your code, but I have one problem to ask your help. The reg loss always changes to Nan after 100steps, when I use mode 'R'. This problem doesn't exist in mode 'H'. The positive anchor sampling in tensorboard shows no problem, so I don't know how to solve it.

**Comment by guoshu6699** [comment]
> problem, so I don't know ho

I also met this problem. Have you solved this problem? If so, tell me how. thank you
