### ISSUE TITLE
您好，如果我想要用DOTA进行训练和测试，我需要做哪些改变呢？

### ISSUE THREAD

**Issue by zsh1234567** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#68]
您好，感谢您的代码。我是该一个初学者，准备用您的代码用dota进行训练和测试。
我需要根据下面的提示进行修改么？感谢您的不吝赐教。
如果进行修改，第（3）步的修改是什么意思呢？需要修改read_tfrecord.py的哪些代码呢？
(1) Modify parameters (such as CLASS_NUM, DATASET_NAME, VERSION, etc.) in $PATH_ROOT/libs/configs/cfgs.py
(2) Add category information in $PATH_ROOT/libs/label_name_dict/lable_dict.py     
(3) Add data_name to $PATH_ROOT/data/io/read_tfrecord.py

**Comment by yangxue0827** [comment]
默认就是DOTA数据集的配置，所以不需要修改，你只要用data/io/DOTA下的脚本处理一下数据，并转成tfrecord格式就可以

**Comment by zsh1234567** [comment]
嗯嗯，谢谢您的指教。我认真专研一下您的文章和代码。再次感谢~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yangxue"<notifications@github.com&gt;; 
发送时间: 2020年4月19日(星期天) 上午8:41
收件人: "DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation"<RetinaNet_Tensorflow_Rotation@noreply.github.com&gt;; 
抄送: "舍之豪"<2532177087@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation] 您好，如果我想要用DOTA进行训练和测试，我需要做哪些改变呢？ (#68)





 
默认就是DOTA数据集的配置，所以不需要修改，你只要用data/io/DOTA下的脚本处理一下数据，并转成tfrecord格式就可以
