### ISSUE TITLE
怎么制作DOTA格式的数据集？how to make costom dataset in format of DOTA?

### ISSUE THREAD

**Issue by Hexuanfang** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#69]

**Comment by yangxue0827** [comment]
照着Pascal VOC的xml格式制作就行

**Comment by Hexuanfang** [comment]
感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yangxue"<notifications@github.com&gt;; 
发送时间: 2020年4月19日(星期天) 上午8:38
收件人: "DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation"<RetinaNet_Tensorflow_Rotation@noreply.github.com&gt;; 
抄送: "煊芳"<972167580@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation] 怎么制作DOTA格式的数据集？how to make costom dataset in format of DOTA? (#69)





 
照着Pascal VOC的xml格式制作就行

**Comment by Hexuanfang** [comment]
还有一个问题想请教：voc是两个点正矩形框，而DOTA是四个点斜框标注，后者使用什么标注工具呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yangxue"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月19日(星期天) 上午8:38
收件人:&nbsp;"DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation"<RetinaNet_Tensorflow_Rotation@noreply.github.com&gt;;
抄送:&nbsp;"煊芳"<972167580@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation] 怎么制作DOTA格式的数据集？how to make costom dataset in format of DOTA? (#69)





 
照着Pascal VOC的xml格式制作就行

**Comment by yangxue0827** [comment]
DOTA的标注工具应该官网有提供，你需要自己联系一下作者 @Hexuanfang
