### ISSUE TITLE
When I train , the loss values often appear at 0.000 and Nan

### ISSUE THREAD

**Issue by liugaolian** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#7]
When I train with my own data, the loss values often appear at 0.000 and Nan. It's strange that with the same data, it's okay to train the R2CNN you share.

**Comment by yangxue0827** [comment]
你把代码回滚到第一版本试试看 @liugaolian

**Comment by yangxue0827** [comment]
能否看一下你的cfgs.py @liugaolian

**Comment by 18804601171** [comment]
> 你把代码回滚到第一版本试试看 @liugaolian 
我也遇到了一样的问题，是什么原因导致的呢，还有就是，我在用1024*1024的图训练时，出现了非法内存访问的错误，是什么原因呢

**Comment by yangxue0827** [comment]
我会更新一下代码 @liugaolian

**Comment by yangxue0827** [comment]
代码已更新，建议先跑通一个默认的配置文件 @liugaolian

**Comment by clw5180** [comment]
> When I train with my own data, the loss values often appear at 0.000 and Nan. It's strange that with the same data, it's okay to train the R2CNN you share.

same problems, how to deal with it?
