### ISSUE TITLE
请问论文中的Feature Refinement Module部分是如何在代码中实现的？

### ISSUE THREAD

**Issue by Hexuanfang** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#70]
https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/acff76b901269dac1199070611ea77a58ce884ac/libs/networks/build_whole_network.py#L224
代码中在build_whole_network.py里，只用了一次rpn_net输出的预测就与真值计算了loss,不知论文中的Feature Refinement Module部分是如何在代码中实现的呢？

**Comment by yangxue0827** [comment]
代码在这：https://github.com/SJTU-Thinklab-Det/R3Det_Tensorflow
@Hexuanfang

**Comment by Hexuanfang** [comment]
感谢感谢！
