### ISSUE TITLE
Test with trained network but return null detection results

### ISSUE THREAD

**Issue by QianGuo123** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#72]
I have trained a network and the result shown in Tensorboard is pretty good. However, when I test the trained network with test dataset, even train dataset, there is no detection bbox.

Did someone ever meet this situation and what should I do?

Thanks very much!

**Comment by liuqianqian77** [comment]
Hello, do you use your own data set for training?

**Comment by QianGuo123** [comment]
Yes, I trained it with my own data whose format is same to DOTA dataset. The train process in Tensorboard is pretty good but it just doesn't work when testing. I think there may be some problem in the test_dota.py but I can't figure it out....

**Comment by liuqianqian77** [comment]
您好，我用中文和您交流吧，我目前遇到了一个问题想请教您一下，我也是用自己的数据集进行训练的，在将数据转tfrocord的时候，我遇到了KeyError: 'eddy\n这个问题，但是一些设置我已经按照作者的进行修改了。期待您的答复，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 上午10:47
收件人:&nbsp;"DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation"<RetinaNet_Tensorflow_Rotation@noreply.github.com&gt;;
抄送:&nbsp;"刘倩倩"<2434070972@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation] Test with trained network but return null detection results (#72)





 
 
 Yes, I trained it with my own data whose format is same to DOTA dataset. The train process in Tensorboard is pretty good but it just doesn't work when testing. I think there may be some problem in the test_dota.py but I can't figure it out....
 | |
 郭倩
 |
 |
 15608225070@163.com
 |
 签名由网易邮箱大师定制
 On 7/30/2020 10:42，liuqianqian77<notifications@github.com&gt; wrote：
 
 Hello, do you use your own data set for training?

**Comment by QianGuo123** [comment]
我没有遇到你这个问题呢，你是用的DOTA格式的数据集吗？ 或许你可以尝试先把数据转成DOTA 格式的然后再跑

**Comment by liuqianqian77** [comment]
恩恩，对的。我看到作者的这个代码里边是将DOTA数据集转成VOC样式的，我是将自己的数据集直接转成VOC样式的了，谢谢您的答复，我再搜索一下找解决方法吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 中午11:00
收件人:&nbsp;"DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation"<RetinaNet_Tensorflow_Rotation@noreply.github.com&gt;;
抄送:&nbsp;"刘倩倩"<2434070972@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation] Test with trained network but return null detection results (#72)





 
我没有遇到你这个问题呢，你是用的DOTA格式的数据集吗？ 或许你可以尝试先把数据转成DOTA 格式的然后再跑

**Comment by QianGuo123** [comment]
啊原来是在test_dota.py的文件中有一个关于网络名称的设置忘改了，修改后问题就解决了
