### ISSUE TITLE
测试的标准问题

### ISSUE THREAD

**Issue by dexterod** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#76]
您好，我想问一下您的这个mAP是在哪里进行测试的啊？
DOTA有train、val、test三个集。
我看了您的代码，是不是可以理解为您在cfgs中标注有：This is your result for task 1 字样的就是对trainval进行训练，然后在DOTA的网站上提交txt得到的mAP结果。
在cfgs中标注有：This is your evaluation result for task 1 字样的就是对train进行训练，然后在val中验证的mAP结果呢？

头好大~~

**Comment by yangxue0827** [comment]
都是对trainval进行训练，然后在DOTA的网站上提交txt得到的mAP结果

**Comment by dexterod** [comment]
哦哦，知道了，谢谢老哥。还有一个疑问，自己想了半天也没明白，网上也找不到：FPN网络里在RoI Pooling层的部分是将不同的RoI分配给金字塔的不同层，分配的公式使用的是FPN论文里的：`levels = tf.round(4. + tf.log(tf.sqrt(w*h + 1e-8)/224.0) / tf.log(2.))`。这里的224是标准ImageNet训练前的图片大小。所以我的疑问是咱们在训练自己的数据集时，比如我的输入图片大小是800×800，为啥这个公式里还是用的224而不是800呢?这个是跟ResNets用ImageNet预训练出来的有关系吗?有点懵，望老哥指点一二~抱拳了~
