### ISSUE TITLE
How to decide CLASS_NUM when training on my own dataset?

### ISSUE THREAD

**Issue by Lanxin1011** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#77]
I have noticed that the CLASS_NUM in cfgs.py is 15, however the actual number of classes of DOTA is 16. Is that mean that if the total classes of my dataset is 10, I should give CLASS_NUM in cfgs.py 9? Hoping to your voice : )
Best regards~

**Comment by yangxue0827** [comment]
In fact, the number of categories provided by DOTA 1.0 is 15, instead of 16.

**Comment by Lanxin1011** [comment]
Thank u so much! I found out just now that DOTA 1.5 has 16 classes, and I guess you gave class_list 16 classes for generalization ability!~
