### ISSUE TITLE
GPU计算RIOU

### ISSUE THREAD

**Issue by 622tongtong** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#84]
iou_rotate_calculate1中利用GPU计算IOU算出来会有大于1的值，不利用GPU模式就是正常的IOU，请问是哪里有问题呢？

**Comment by yangxue0827** [comment]
具体例子呢？

**Comment by 622tongtong** [comment]
def iou_rotate_calculate1(boxes1, boxes2, use_gpu=True, gpu_id=0):

    # start = time.time()

    if use_gpu:
        ious = rbbx_overlaps(boxes1, boxes2, gpu_id)
    else:
        area1 = boxes1[:, 2] * boxes1[:, 3]
        area2 = boxes2[:, 2] * boxes2[:, 3]
        ious = []
        for i, box1 in enumerate(boxes1):
            temp_ious = []
            r1 = ((box1[0], box1[1]), (box1[2], box1[3]), box1[4])
            for j, box2 in enumerate(boxes2):
                r2 = ((box2[0], box2[1]), (box2[2], box2[3]), box2[4])

                int_pts = cv2.rotatedRectangleIntersection(r1, r2)[1]
                if int_pts is not None:
                    order_pts = cv2.convexHull(int_pts, returnPoints=True)

                    int_area = cv2.contourArea(order_pts)

                    inter = int_area * 1.0 / (area1[i] + area2[j] - int_area)
                    temp_ious.append(inter)
                else:
                    temp_ious.append(0.0)
            ious.append(temp_ious)

    # print('{}s'.format(time.time() - start))

    return np.array(ious, dtype=np.float32)
这个函数，利用gpu，或者不用，输入的都是边界框的5参数模式，用gpu计算出的结果存在大于1的，gpu=False的结果都在1以内

**Comment by yangxue0827** [comment]
你得给我一个具体的例子。

**Comment by 622tongtong** [comment]
具体的例子，是源代码吗？

**Comment by yangxue0827** [comment]
哪两个框算出来大于1。代码我自己能不清楚吗。

**Comment by 622tongtong** [comment]
target：[  0.00000,   0.00000,   1.32031,   0.22607, -51.36830]
prediction：[  0.00000,   0.00000,   1.40039,   1.19531, -82.40114]
gpu算出来: 2.21053

**Comment by yangxue0827** [comment]
那是因为边太小造成的数值问题，你可以加一个判断，边太小的iou直接是0。

**Comment by yangxue0827** [comment]
一般框的长宽不会这么小，尤其不会小于1

**Comment by 622tongtong** [comment]
哦哦，搜嘎，谢谢你哟~
